version: "3.9"

services:
  api:
    build:
      context: .
    container_name: garage_api
    env_file:
      - .env
    environment:
      APP_ENV: ${APP_ENV:-production}
      SECRET_KEY: ${SECRET_KEY:-changeme-in-prod}
      DATABASE_URL: ${DATABASE_URL}
      UPLOADS_DIR: /app/uploads
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

  scheduler:
    build:
      context: .
    container_name: garage_scheduler
    env_file:
      - .env
    environment:
      API_BASE_URL: ${API_BASE_URL:-http://api:8000}
      APP_ENV: ${APP_ENV:-production}
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY:-changeme-in-prod}
      ADMIN_EMAIL: ${ADMIN_EMAIL:-admin@garage.local}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-change-me}
    depends_on:
      - api
    restart: unless-stopped
    command: ["./docker/scheduler.sh"]

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: ${FRONTEND_API_BASE_URL:-http://api:8000}
    container_name: garage_frontend
    ports:
      - "${FRONTEND_PORT:-4173}:80"
    depends_on:
      - api
    restart: unless-stopped

